# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build-prod

    - run: git clone -b "${GITHUB_REF##*/}"-dist --single-branch https://github.com/${GITHUB_REPOSITORY}.git tmpFolder
    
    # - run: cd tmpFolder && pwd && ls

    - run: rm -rf tmpFolder/*
    
    # - run: cp -rf  home/runner/work/matemaraton/matemaraton/dist/* home/runner/work/matemaraton/matemaraton/tmpFolder
    - run: cd tmpFolder && cp -rf  ./dist/* .
    
    - run: cd tmpFolder && cp  ./package.json package.json
    - run: cd tmpFolder && npm install --omit=dev
    - run: cd tmpFolder && rm -f package.json package-lock.json
    - run: cd tmpFolder && git add -A
    - run: cd tmpFolder && git commit -m "."
    - run: git config --global user.name "${github.repository_owner}"
    - run: git config --global push.default simple
    - run: cd tmpFolder &&git push origin
    
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    
